version: '3.7'

services:
  filebeat:
    image: tamusiunas/filebeat
    container_name: filebeat
    user: root
    network_mode: host
    volumes:
      - /storage/.docker/data-root/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /storage/.docker/volumes/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    environment:
      - KIBANA_HOST=#PUT HERE KIBANA HOST IP ADDRESS OR NAME#
      - ELASTICSEARCH_HOSTS=#PUT HERE ELASTIC SEARCH HOST IP ADDRESS OR NAME#
      - ELASTICSEARCH_USERNAME=elastic # This is the default username. If it's different from yours, change it
      - ELASTICSEARCH_PASSWORD=changeme # #This is the default password. If it's different from yours, change it
      - TZ=Europe/London
    command: -strict.perms=false
    restart: unless-stopped
    deploy:
      mode: global

