heartbeat.monitors:
- type: http
  enabled: true
  schedule: '@every 5s'
  urls:
    - http://elasticsearch:9200
    - http://kibana:5601

- type: icmp
  enabled: true
  schedule: '@every 5s'
  hosts:
    - elasticsearch
    - kibana

processors:
  - add_docker_metadata: ~
  - add_host_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

setup.kibana:
  host: '${KIBANA_HOST:kibana:5601}'

monitoring.enabled: true

setup.dashboards.enabled: false

