version: '3.7'

services:
  journalbeat:
    image: tamusiunas/journalbeat
    container_name: journalbeat
    user: root
    network_mode: host
    volumes:
      - /run/log/journal:/var/log/journal
      - /etc/machine-id:/etc/machine-id
      - /run/systemd:/run/systemd
      - /etc/hostname:/etc/hostname:ro
    environment:
      - KIBANA_HOST=#PUT HERE KIBANA HOST IP ADDRESS OR NAME#
      - ELASTICSEARCH_HOSTS=#PUT HERE ELASTIC SEARCH HOST IP ADDRESS OR NAME#
      - ELASTICSEARCH_USERNAME=elastic # This is the default username. If it's different from yours, change it
      - ELASTICSEARCH_PASSWORD=changeme # #This is the default password. If it's different from yours, change it
      - TZ=Europe/London
    command: -strict.perms=false
    restart: unless-stopped
    deploy:
      mode: global

