version: "2.1"
services:
  ddclient:
    image: ghcr.io/linuxserver/ddclient
    container_name: ddclient
    environment:
      - TZ=Europe/London
    volumes:
      - /storage/.docker/volumes/ddclient/config:/config
    restart: unless-stopped
